export const ROLES = { SALESMAN: 'SALESMAN', ADMIN: 'ADMIN' };

export const BILL_STATES = { DUE: 'PENDIENTE', PAID: 'PAGO', CREDIT: 'A CREDITO' }

export const PAYMENT_METHODS = { CASH: 'EFECTIVO', NEQUI: 'NEQUI' };