export const ROLES = { SALESMAN: 'SALESMAN', ADMIN: 'ADMIN' };

export const BILL_STATES = { DUE: 'PENDIENTE', PAID: 'PAGO', CREDIT: 'A CREDITO' }

export const PAYMENT_METHODS = { 
    CASH: 'EFECTIVO', 
    NEQUI: 'NEQUI', 
    DAVIPLATA: 'DAVIPLATA',
    BANCOLOMBIA: 'BANCOLOMBIA'
};

export const BOLIRANAS_STATES = { BUSY: 'OCUPADA', AVAILABLE: 'LIBRE' }